apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: simple
  namespace: stackgres
spec:
  managedSql:
    scripts:
    - sgScript: enable-timescaledb
  instances: 1
  postgres:
    version: '14'
    extensions:
      - {name: 'timescaledb', version: '2.17.2'}
  configurations:
    sgPostgresConfig: 'pgconfig'
    sgPoolingConfig: 'poolconfig'
    backups:
    - sgObjectStorage: 'backupconfig'
      # cronSchedule: '* * * * *'
      retention: 4
    observability: 
      disableMetrics: true
      prometheusAutobind: false
  pods:
    disableConnectionPooling: true
    disableMetricsExporter: false
    disablePostgresUtil: false
    persistentVolume: 
      size: '5Gi'
      storageClass: default
  

      